name: Slack Alert Notification

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Thank you for opening issue/pr, ${{ env.GITHUB_USERNAME }}!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Thank you for opening issue/pr, ${{ env.GITHUB_USERNAME }}!"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          GITHUB_USERNAME: ${{github.actor}}
